name: 'markdown-test-docs-action'
description: 'Generate markdown documentation from TypeScript/Jest/Vitest test files'
author: 'Szymon Paluchowski'

inputs:
  source:
    description: 'Source directory containing test files'
    required: false
    default: ''
  output:
    description: 'Output directory for generated documentation'
    required: false
    default: ''
  github-url:
    description: 'GitHub repository URL for source links'
    required: false
    default: ''
  github-branch:
    description: 'GitHub branch name'
    required: false
    default: 'main'
  repository-root:
    description: 'Repository root directory'
    required: false
    default: ''
  verbose:
    description: 'Enable verbose logging'
    required: false
    default: 'false'

outputs:
  success:
    description: 'Whether the documentation generation was successful'
  output-dir:
    description: 'The directory where documentation was generated'
  framework-detected:
    description: 'The test framework that was detected/used'
  total-files:
    description: 'Total number of test files processed'
  total-tests:
    description: 'Total number of tests documented'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'book-open'
  color: 'blue'