name: Generate Vitest Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate Test Documentation
      uses: ./
      with:
        source: 'src/test'
        output: 'docs/tests'
        github-url: ${{ github.server_url }}/${{ github.repository }}
        github-branch: ${{ github.ref_name }}
        repository-root: '.'
        test-framework: 'vitest'
        verbose: 'true'
    
    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: test-documentation
        path: docs/tests/
    
    - name: Deploy to GitHub Pages (optional)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/tests
