name: Generate Markdown Documentation

on:
  push:
    paths:
      - "src/**/*.test.js"
      - "src/**/*.test.ts"
      - "src/**/*.spec.js"
      - "src/**/*.spec.ts"
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate Markdown Docs with GitHub Links
        uses: ./.github/actions/markdown-test-docs
        with:
          source: "./src"
          output: "./doc/tests"
          github-url: ${{ github.server_url }}/${{ github.repository }}
          github-branch: ${{ github.ref_name }}
          repository-root: "./"

      - name: Commit Documentation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./doc/tests
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update generated markdown documentation [skip ci]"
            git push
          fi